name: MoreDupes
version: '1.0.0'
main: com.mistasoup.moredupes.MoreDupes
api-version: '1.21'
folia-supported: true
author: MistaSoup
description: Multiple item duplication methods for Minecraft servers
commands:
  moredupesreload:
    description: Reloads the MoreDupes configuration
    usage: /moredupesreload
    permission: moredupes.reload
    aliases: [mdr, mdreload]
permissions:
  moredupes.reload:
    description: Allows reloading the plugin configuration
    default: op